### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by brvtl** [kvey/cljpokego#1]
cljpokego git:(master) lein protobuf
Downloading protobuf-2.6.1.zip to /home/peter/.lein/cache/lein-protobuf/protobuf-2.6.1.zip
Unzipping /home/peter/.lein/cache/lein-protobuf/protobuf-2.6.1.zip to /home/peter/.lein/cache/lein-protobuf/protobuf-2.6.1
Configuring protoc
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define **EXTENSIONS**... yes
checking C++ compiler flags...... use default: -O2  -g -DNDEBUG
checking whether __SUNPRO_CC is declared... no
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for working memcmp... yes
checking for working strtod... yes
checking for ftruncate... yes
checking for memset... yes
checking for mkdir... yes
checking for strchr... yes
checking for strerror... yes
checking for strtol... yes
checking zlib version... ok (1.2.0.4 or later)
checking for library containing zlibVersion... -lz
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking whether what we have so far is sufficient with -nostdlib... no
checking whether -lpthread saves the day... yes
checking the location of hash_map... <tr1/unordered_map>
checking for library containing sched_yield... none required
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating protobuf.pc
config.status: creating protobuf-lite.pc
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
=== configuring in gtest (/home/peter/.lein/cache/lein-protobuf/protobuf-2.6.1/gtest)
configure: running /bin/bash ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for python... /usr/bin/python
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating scripts/gtest-config
config.status: creating build-aux/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
Running 'make'
 cd . && /bin/bash /home/peter/.lein/cache/lein-protobuf/protobuf-2.6.1/missing automake-1.14 --foreign
Makefile:612: recipe for target 'Makefile.in' failed

>  /home/peter/.lein/cache/lein-protobuf/protobuf-2.6.1/src/protoc pokemongo.proto --java_out=/home/peter/code/poke/cljpokego/cljpokego/target/protosrc -I. -I/home/peter/code/poke/cljpokego/cljpokego/target/proto -I/home/peter/code/poke/cljpokego/cljpokego/resources/proto
> java.io.IOException: Cannot run program "/home/peter/.lein/cache/lein-protobuf/protobuf-2.6.1/src/protoc" (in directory "resources/proto"): error=2, No such file or directory
>  at java.lang.ProcessBuilder.start (ProcessBuilder.java:1048)
>     java.lang.Runtime.exec (Runtime.java:620)
>     sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
>     sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     java.lang.reflect.Method.invoke (Method.java:498)
>     clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:93)
>     clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:28)
>     conch.core$proc.invokeStatic (core.clj:23)
>     conch.core$proc.doInvoke (core.clj:15)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invokeStatic (core.clj:646)
>     clojure.core$apply.invoke (core.clj:641)
>     leiningen.protobuf$compile_protobuf.invokeStatic (protobuf.clj:134)
>     leiningen.protobuf$compile_protobuf.invoke (protobuf.clj:111)
>     leiningen.protobuf$compile_protobuf.invokeStatic (protobuf.clj:114)
>     leiningen.protobuf$compile_protobuf.invoke (protobuf.clj:111)
>     leiningen.protobuf$protobuf.invokeStatic (protobuf.clj:163)
>     leiningen.protobuf$protobuf.doInvoke (protobuf.clj:155)
>     clojure.lang.RestFn.invoke (RestFn.java:410)
>     clojure.lang.Var.invoke (Var.java:379)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invokeStatic (core.clj:648)
>     clojure.core$apply.invoke (core.clj:641)
>     leiningen.core.main$partial_task$fn__5829.doInvoke (main.clj:272)
>     clojure.lang.RestFn.invoke (RestFn.java:410)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.RestFn.applyTo (RestFn.java:132)
>     clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invokeStatic (core.clj:648)
>     clojure.core$apply.invoke (core.clj:641)
>     leiningen.core.main$apply_task.invokeStatic (main.clj:322)
>     leiningen.core.main$apply_task.invoke (main.clj:308)
>     lein_environ.plugin$write_env_to_file.invokeStatic (plugin.clj:11)
>     lein_environ.plugin$write_env_to_file.invoke (plugin.clj:9)
>     clojure.lang.Var.invoke (Var.java:394)
>     clojure.lang.AFn.applyToHelper (AFn.java:165)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invokeStatic (core.clj:648)
>     clojure.core$apply.invoke (core.clj:641)
>     robert.hooke$compose_hooks$fn__11923.doInvoke (hooke.clj:40)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invokeStatic (core.clj:646)
>     clojure.core$apply.invoke (core.clj:641)
>     robert.hooke$run_hooks.invokeStatic (hooke.clj:46)
>     robert.hooke$run_hooks.invoke (hooke.clj:45)
>     robert.hooke$prepare_for_hooks$fn__11928$fn__11929.doInvoke (hooke.clj:54)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
>     clojure.lang.RestFn.invoke (RestFn.java:436)
>     leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
>     leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
>     leiningen.core.main$_main$fn__5895.invoke (main.clj:401)
>     leiningen.core.main$_main.invokeStatic (main.clj:394)
>     leiningen.core.main$_main.doInvoke (main.clj:391)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.lang.Var.invoke (Var.java:379)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invokeStatic (core.clj:646)
>     clojure.main$main_opt.invokeStatic (main.clj:314)
>     clojure.main$main_opt.invoke (main.clj:310)
>     clojure.main$main.invokeStatic (main.clj:421)
>     clojure.main$main.doInvoke (main.clj:384)
>     clojure.lang.RestFn.invoke (RestFn.java:436)
>     clojure.lang.Var.invoke (Var.java:388)
>     clojure.lang.AFn.applyToHelper (AFn.java:160)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.main.main (main.java:37)
> Caused by: java.io.IOException: error=2, No such file or directory
>  at java.lang.UNIXProcess.forkAndExec (UNIXProcess.java:-2)
>     java.lang.UNIXProcess.<init> (UNIXProcess.java:248)
>     java.lang.ProcessImpl.start (ProcessImpl.java:134)
>     java.lang.ProcessBuilder.start (ProcessBuilder.java:1029)
>     java.lang.Runtime.exec (Runtime.java:620)
>     sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
>     sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     java.lang.reflect.Method.invoke (Method.java:498)
>     clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:93)
>     clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:28)
>     conch.core$proc.invokeStatic (core.clj:23)
>     conch.core$proc.doInvoke (core.clj:15)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invokeStatic (core.clj:646)
>     clojure.core$apply.invoke (core.clj:641)
>     leiningen.protobuf$compile_protobuf.invokeStatic (protobuf.clj:134)
>     leiningen.protobuf$compile_protobuf.invoke (protobuf.clj:111)
>     leiningen.protobuf$compile_protobuf.invokeStatic (protobuf.clj:114)
>     leiningen.protobuf$compile_protobuf.invoke (protobuf.clj:111)
>     leiningen.protobuf$protobuf.invokeStatic (protobuf.clj:163)
>     leiningen.protobuf$protobuf.doInvoke (protobuf.clj:155)
>     clojure.lang.RestFn.invoke (RestFn.java:410)
>     clojure.lang.Var.invoke (Var.java:379)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invokeStatic (core.clj:648)
>     clojure.core$apply.invoke (core.clj:641)
>     leiningen.core.main$partial_task$fn__5829.doInvoke (main.clj:272)
>     clojure.lang.RestFn.invoke (RestFn.java:410)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.RestFn.applyTo (RestFn.java:132)
>     clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invokeStatic (core.clj:648)
>     clojure.core$apply.invoke (core.clj:641)
>     leiningen.core.main$apply_task.invokeStatic (main.clj:322)
>     leiningen.core.main$apply_task.invoke (main.clj:308)
>     lein_environ.plugin$write_env_to_file.invokeStatic (plugin.clj:11)
>     lein_environ.plugin$write_env_to_file.invoke (plugin.clj:9)
>     clojure.lang.Var.invoke (Var.java:394)
>     clojure.lang.AFn.applyToHelper (AFn.java:165)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invokeStatic (core.clj:648)
>     clojure.core$apply.invoke (core.clj:641)
>     robert.hooke$compose_hooks$fn__11923.doInvoke (hooke.clj:40)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invokeStatic (core.clj:646)
>     clojure.core$apply.invoke (core.clj:641)
>     robert.hooke$run_hooks.invokeStatic (hooke.clj:46)
>     robert.hooke$run_hooks.invoke (hooke.clj:45)
>     robert.hooke$prepare_for_hooks$fn__11928$fn__11929.doInvoke (hooke.clj:54)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
>     clojure.lang.RestFn.invoke (RestFn.java:436)
>     leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
>     leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
>     leiningen.core.main$_main$fn__5895.invoke (main.clj:401)
>     leiningen.core.main$_main.invokeStatic (main.clj:394)
>     leiningen.core.main$_main.doInvoke (main.clj:391)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.lang.Var.invoke (Var.java:379)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invokeStatic (core.clj:646)
>     clojure.main$main_opt.invokeStatic (main.clj:314)
>     clojure.main$main_opt.invoke (main.clj:310)
>     clojure.main$main.invokeStatic (main.clj:421)
>     clojure.main$main.doInvoke (main.clj:384)
>     clojure.lang.RestFn.invoke (RestFn.java:436)
>     clojure.lang.Var.invoke (Var.java:388)
>     clojure.lang.AFn.applyToHelper (AFn.java:160)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.main.main (main.java:37)

**Comment by kvey** [comment]
I think you ran lein protobuf from the top level directory instead of cljpokego. I'll move everything into one directory, it might cause less confusion.

**Comment by brvtl** [comment]
I ran it from the correct folder. I even removed my ~/.m2 folder and re-ran it

cljpokego git:(master) pwd
/home/me/code/poke/cljpokego/cljpokego

**Comment by kvey** [comment]
Sorry, you're correct. I was in a rush and didnt read that correctly. 
You could try installing protoc separately first if you want to just try now. This is a problem with installing lein-protobuf.





On Wed, Jul 27, 2016 at 12:19 PM -0700, "Peter Garbers" <notifications@github.com> wrote:












I don't believe I did that. I just checked that. In fact

**Comment by kvey** [comment]
This was an issue with lein-protobuf installation. I've removed it from the dependencies and included the java source in the repo. If any changes are made to the .proto definition, protoc can be used to regenerate the java source.

Sorry about my earlier response.
